// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nkukxprgwhvsjvmqqwsz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5rdWt4cHJnd2h2c2p2bXFxd3N6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgxNzY4MDIsImV4cCI6MjA1Mzc1MjgwMn0.sbd40TQkiJ19BuP4jyIGgoOklq5ZoIp9RMAjfA7D_bs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);